### ISSUE TITLE
Lisenssi

### ISSUE THREAD

**Issue by rkantos** [bambora/payform-php-lib#1]
Millasella lisenssillä näitä voi käyttää vai onko tarkoitettu vain puhtaasti mallinottoon? :+1:

**Comment by msalmine** [comment]
Saa käyttää ihan vapaasti mihin tarkoitukseen hyvänsä.

**Comment by rkantos** [comment]
Voisiko kuitenkin lisätä vaikka MIT-lisenssin, niin tekisi ainakin kaikesta selvää, eli voisi suoraan kopioida käytännössä kaikkiin muihin projekteihin. Muilla on muitakin lisenssejä,  kuten Checkout Finlandilla, jolla on käytössä Apachen 2.0. 

https://choosealicense.com/

**Comment by msalmine** [comment]
Kiitos vinkistä, lisenssi lisätty repoon.
